"""initial migration.

Revision ID: fc3be2459aa6
Revises: 
Create Date: 2025-03-24 14:29:40.587009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3be2459aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('projects', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
