# Generated by Django 5.1.6 on 2025-03-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='_id',
            field=models.CharField(blank=True, default='67dcd038463f36266c98fbb0', editable=False, max_length=24),
        ),
    ]
